// <auto-generated />
using System;
using Ap2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ap2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Ap2.Domain.Entities.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId")
                        .IsUnique();

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("Ap2.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Veiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Ap2.Domain.Entities.Carro", b =>
                {
                    b.HasBaseType("Ap2.Domain.Entities.Veiculo");

                    b.HasDiscriminator().HasValue("Carro");
                });

            modelBuilder.Entity("Ap2.Domain.Entities.Moto", b =>
                {
                    b.HasBaseType("Ap2.Domain.Entities.Veiculo");

                    b.HasDiscriminator().HasValue("Moto");
                });

            modelBuilder.Entity("Ap2.Domain.Entities.Vaga", b =>
                {
                    b.HasOne("Ap2.Domain.Entities.Veiculo", "Estacionado")
                        .WithOne()
                        .HasForeignKey("Ap2.Domain.Entities.Vaga", "VeiculoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Estacionado");
                });
#pragma warning restore 612, 618
        }
    }
}
